version: "3"
services:
  mysqldb:
    image: mysql/mysql-server:latest
    ports:
      - "3066:3066"
    networks:
      - its-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ITS
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root

  its-be:
    image: its
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9096:9096"
    networks:
      - its-mysql
    depends_on:
      - mysqldb
networks:
  its-mysql: